In [1]:
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3],[4, 5, 6]])
array3 = np.array([[1,2,3]])

print('array1 type: ', type(array1))
print('array1 형태: ', array1.shape)


array1 type:  <class 'numpy.ndarray'>
array1 형태:  (3,)


In [2]:
print('array2 형태: ', array2.shape)
print('array3 형태: ', array3.shape)

array2 형태:  (2, 3)
array3 형태:  (1, 3)


In [3]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [4]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [5]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [6]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [7]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)


[[0 0]
 [0 0]
 [0 0]]


In [10]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array2 = array1.reshape(-1, 5)
array3 = array1.reshape(5, -1)

print(array2)
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('arrayy3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:',array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:',array6.shape)


arrayy3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)
